sudo: false
services:
  - postgresql
language: node_js
node_js:
- 10.13.0
before_install:
- npm install -g codecov
install:
- npm install
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - psql -U postgres -c 'create database ireporter;'
script:
- npm run initdb
- npm test
install:
- npm install
cache:
  directories:
  - "$HOME/.npm"

deploy:
  provider: heroku
  api_key:
    secure: K7o7GGum4r6lUROVe0xMYi/+21c9XoosSdpymtRmGu0g/Oms+tg0W3os0hjXdx+RMLdQh0ON9SOBDeuJ8nyXhXs1YuYEhNqjWEES30E5ArSWxmCrdA5SXDGtwfvO6TF2qRWta2Hu3kVIkHtVGYbbde8GAlhO37LPFWPgjzVj4FDB059pRQWQp6LLgo3TjTpPsXpL97Z5CeJ8DrvEdKK06UtDsudeLMQzZxQoO65wXVFXpH4OqSNYyaXv1snX4s+pv72lomHLqv3qEw/WPjfd5TGYRJfxAZKHWESoEoKDeQak6cGjcRgfJOa52e+OfZAWHYOQTV7E877IQGSupoNd6Z3vOEReqTfasHW3YDd7fOqlUysNZ1Rpq+l3GCbFX2JgIkIFLVI8vhGKp3ZoolEVcNyF0MHq0BzX1XpMiWegOgFY7k9hgOwqSxn6JEQOjO2aoZjASzTYAfCRaDcFVl+zvo/f9GjvhgsSwD+Zq0k7AsS/xuTVDc/SIw9qID7bPa9n6pSNCGNYFDnMUu7SatYR7ZB21kbA12qeWBfzRBzIHaWzDDSdjqJIx9MPtCdoldFtguGNtP3/8jdg9ZG6nf1FbG3SKsDEtwsEMPyP0/z1E977ImYMkURHNJdEs1PPY69mT6uU5pnK3Pdl2lCQY7rIJRXRptpd7MvraZhOj8k5sNQ=
  app:
    develop: ireporter-pms
after_success: npm run coverage
